version: "3.8"

services:
  frontend:
    container_name: frontend
    build:
      context: ./
      dockerfile: ./build_env/frontend/${DOCKERFILE}
    restart: always
    ports:
      - ${FRONTEND_PORTS}
    depends_on:
      - backend
      - s3

  backend:
    container_name: backend
    build:
      context: ./
      dockerfile: ./build_env/backend/${DOCKERFILE}
    restart: always
    ports:
      - 4000:4000
    environment:
      - S3_BUCKET_NAME=my-bucket
      - S3_ENDPOINT=http://s3:9000
      - S3_ACCESS_KEY=minioadmin
      - S3_SECRET_KEY=minioadmin
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    depends_on:
      - db
      - s3

  s3:
    container_name: s3
    image: minio/minio
    restart: always
    command: server /data --console-address ":9001"
    volumes:
      - ./data:/data
    environment:
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin

  db:
    container_name: db
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data

volumes:
  data:
  pgdata: