# Fetching the latest node image on apline linux
FROM node:alpine AS builder

# Declaring env
ENV NODE_ENV development

# Setting up the work directory
WORKDIR /app

# Installing dependencies
COPY ./frontend/package.json ./frontend/package-lock.json ./
RUN npm install

# Copying all the files in our project
COPY ./frontend/. .

# Building our application
# RUN npm run build

ENTRYPOINT ["npm", "run"]
CMD ["web"]

